# add the following to _config.yml file
title: SEDJARI Yassine
logo: /images/yassine.jpeg
contact:
  email: example@email.com
  phone: 123-456-7890
  address: 123 Main St, City, Country
theme: jekyll-theme-minimal
